# From https://medium.com/@johnjjung/building-an-electron-app-on-github-actions-windows-and-macos-53ab69703f7c
name: CI

# Run on push to 'release branch or master' branch
on: push

# List contents
jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.S3_BUCKET_REGION }}
      - name: Rearrange file for s3
        run: |
          mkdir s3Folder
          cd s3Folder
          touch test1.txt
          touch test2.txt
          mkdir mac
          cd mac
          mv ../test1.txt .
          cd ../
          mkdir win
          cd win
          mv ../test2.txt .
          cd ../
          ls
      - name: Upload to s3
        uses: reggionick/s3-deploy@v3
        with:
          # the folder we have just created, with all our resource
          folder: s3Folder
          bucket: ${{ secrets.S3_BUCKET }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true
