# From https://medium.com/@johnjjung/building-an-electron-app-on-github-actions-windows-and-macos-53ab69703f7c
name: CI

# Run on push to 'release branch or master' branch
on: push

# List contents
jobs:
  build_on_mac2:
    runs-on: macOS-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.S3_BUCKET_REGION }}
      - name: Rearrange file for s3
        run: |
          mkdir s3Folder
          touch test1.txt
          touch test2.txt
          cd s3Folder
          mkdir dev
          cd dev
          mkdir mac
          mkdir win
          cd ../../
          cp ./test1.txt ./s3Folder/dev/mac/test1.txt
          cp ./test2.txt ./s3Folder/dev/win/test2.txt

          ls

      # - name: Upload to s3
      #   uses: reggionick/s3-deploy@v3
      #   with:
      #     # the folder we have just created, with all our resource
      #     folder: s3Folder
      #     bucket: ${{ secrets.S3_BUCKET }}
      #     dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
      #     bucket-region: ${{ secrets.S3_BUCKET_REGION }}
      #     invalidation: /
      #     delete-removed: true
      #     no-cache: true
      #     private: true
